/**
 * Element Plus 图标配置文件
 *
 * 集中管理所有可用的 Element Plus 图标
 * 版本: @element-plus/icons-vue@2.3.2
 * 来源: https://cn.element-plus.org/zh-CN/component/icon.html
 */

import {
  // 系统图标
  Plus,
  Minus,
  CirclePlus,
  Search,
  Female,
  Male,
  Aim,
  House,
  FullScreen,
  Loading,
  Link,
  Service,
  Pointer,
  Star,
  Notification,
  Connection,
  ChatDotRound,
  Setting,
  Clock,
  Position,
  Discount,
  Odometer,
  ChatSquare,
  ChatRound,
  ChatLineRound,
  ChatLineSquare,
  ChatDotSquare,
  View,
  Hide,
  Unlock,
  Lock,
  RefreshRight,
  RefreshLeft,
  Refresh,
  Bell,
  MuteNotification,
  User,
  Check,
  Close,
  PieChart,
  More,
  Compass,
  Filter,
  Switch,
  Select,
  SemiSelect,
  CloseBold,
  EditPen,
  Edit,
  Message,
  MessageBox,
  TurnOff,
  Finished,
  Delete,
  Crop,
  SwitchButton,
  Operation,
  Open,
  Remove,
  ZoomOut,
  ZoomIn,

  // 填充图标
  InfoFilled,
  CircleCheckFilled,
  SuccessFilled,
  CircleCloseFilled,
  QuestionFilled,
  WarnTriangleFilled,
  UserFilled,
  MoreFilled,
  Tools,
  HomeFilled,
  Menu,
  UploadFilled,
  Avatar,
  HelpFilled,
  Share,
  StarFilled,
  Comment,
  Histogram,
  Grid,
  Promotion,
  DeleteFilled,
  RemoveFilled,
  CirclePlusFilled,

  // 箭头图标
  ArrowLeft,
  ArrowUp,
  ArrowRight,
  ArrowDown,
  ArrowLeftBold,
  ArrowUpBold,
  ArrowRightBold,
  ArrowDownBold,
  DArrowRight,
  DArrowLeft,
  Download,
  Upload,
  Top,
  Bottom,
  Back,

  // 排序图标
  Sort,
  SortUp,
  SortDown,
  Rank,
  CaretLeft,
  CaretTop,
  CaretRight,
  CaretBottom,
  Expand,
  Fold,

  // 文档图标
  Document,
  DocumentAdd,
  Tickets,
  Memo,
  Collection,
  Postcard,
  ScaleToOriginal,
  SetUp,
  DocumentDelete,
  DocumentChecked,
  DataBoard,
  DataAnalysis,
  CopyDocument,
  FolderChecked,
  Files,
  Folder,
  FolderDelete,
  FolderRemove,
  FolderOpened,
  DocumentCopy,
  DocumentRemove,
  FolderAdd,
  FirstAidKit,
  Reading,
  DataLine,
  Management,
  Checked,
  TrendCharts,
  List,
  Microphone,
  VideoPause,
  VideoCamera,
  VideoPlay,
  Headset,
  Monitor,
  Film,
  Camera,
  Picture,
  PictureRounded,
  Iphone,
  Cellphone,
  VideoCameraFilled,
  PictureFilled,
  Platform,
  CameraFilled,
  BellFilled,
  Location,
  LocationInformation,
  DeleteLocation,
  Coordinate,
  Bicycle,
  OfficeBuilding,
  School,
  Guide,
  AddLocation,
  MapLocation,
  Place,
  LocationFilled,
  Van,
  Food,
  Watermelon,
  Pear,
  NoSmoking,
  Smoking,
  Mug,
  GobletSquareFull,
  GobletFull,
  KnifeFork,
  MilkTea,
  Lollipop,
  Coffee,
  Chicken,
  Dish,
  IceTea,
  ColdDrink,
  CoffeeCup,
  DishDot,
  IceDrink,
  IceCream,
  Dessert,
  IceCreamSquare,
  ForkSpoon,
  IceCreamRound,
  Grape,
  Fries,
  Apple,
  Burger,
  Goblet,
  GobletSquare,
  Orange,
  Cherry,
  Printer,
  Calendar,
  CreditCard,
  Box,
  Money,
  Refrigerator,
  Cpu,
  Football,
  Brush,
  Suitcase,
  SuitcaseLine,
  Umbrella,
  AlarmClock,
  Medal,
  GoldMedal,
  Present,
  Mouse,
  Watch,
  QuartzWatch,
  Magnet,
  Help,
  Soccer,
  ToiletPaper,
  ReadingLamp,
  Paperclip,
  MagicStick,
  Basketball,
  Baseball,
  Coin,
  Goods,
  Sell,
  SoldOut,
  Key,
  ShoppingCart,
  ShoppingCartFull,
  ShoppingTrolley,
  Phone,
  Scissor,
  Handbag,
  ShoppingBag,
  Trophy,
  TrophyBase,
  Stopwatch,
  Timer,
  CollectionTag,
  TakeawayBox,
  PriceTag,
  Wallet,
  Opportunity,
  PhoneFilled,
  WalletFilled,
  GoodsFilled,
  Flag,
  BrushFilled,
  Briefcase,
  Stamp,

  // 天气图标
  Sunrise,
  Sunny,
  Ship,
  MostlyCloudy,
  PartlyCloudy,
  Sunset,
  Drizzling,
  Pouring,
  Cloudy,
  Moon,
  MoonNight,
  Lightning,

  // 浏览器图标
  ChromeFilled,
  Eleme,
  ElemeFilled,
  ElementPlus,
  Shop,
  SwitchFilled,
  WindPower
} from '@element-plus/icons-vue'

/**
 * 所有可用的图标配置列表
 * 结构: { name: string, component: Component, category: string }
 */
export const availableIcons = [
  // ==================== 核心常用图标 ====================
  { name: 'HomeFilled', component: HomeFilled, category: 'core' },
  { name: 'House', component: House, category: 'core' },
  { name: 'Grid', component: Grid, category: 'core' },
  { name: 'Menu', component: Menu, category: 'core' },
  { name: 'Search', component: Search, category: 'core' },
  { name: 'Plus', component: Plus, category: 'core' },
  { name: 'Minus', component: Minus, category: 'core' },
  { name: 'Close', component: Close, category: 'core' },
  { name: 'Setting', component: Setting, category: 'core' },
  { name: 'Star', component: Star, category: 'core' },
  { name: 'StarFilled', component: StarFilled, category: 'core' },
  { name: 'More', component: More, category: 'core' },
  { name: 'MoreFilled', component: MoreFilled, category: 'core' },

  // ==================== 编辑操作图标 ====================
  { name: 'Edit', component: Edit, category: 'edit' },
  { name: 'EditPen', component: EditPen, category: 'edit' },
  { name: 'Delete', component: Delete, category: 'edit' },
  { name: 'DeleteFilled', component: DeleteFilled, category: 'edit' },
  { name: 'Remove', component: Remove, category: 'edit' },
  { name: 'RemoveFilled', component: RemoveFilled, category: 'edit' },
  { name: 'CopyDocument', component: CopyDocument, category: 'edit' },
  { name: 'Scissor', component: Scissor, category: 'edit' },
  { name: 'Brush', component: Brush, category: 'edit' },
  { name: 'BrushFilled', component: BrushFilled, category: 'edit' },
  { name: 'Crop', component: Crop, category: 'edit' },
  { name: 'Filter', component: Filter, category: 'edit' },
  { name: 'Sort', component: Sort, category: 'edit' },
  { name: 'SortUp', component: SortUp, category: 'edit' },
  { name: 'SortDown', component: SortDown, category: 'edit' },
  { name: 'Rank', component: Rank, category: 'edit' },

  // ==================== 数据图表图标 ====================
  { name: 'TrendCharts', component: TrendCharts, category: 'data' },
  { name: 'DataLine', component: DataLine, category: 'data' },
  { name: 'DataAnalysis', component: DataAnalysis, category: 'data' },
  { name: 'DataBoard', component: DataBoard, category: 'data' },
  { name: 'Histogram', component: Histogram, category: 'data' },
  { name: 'PieChart', component: PieChart, category: 'data' },
  { name: 'List', component: List, category: 'data' },

  // ==================== 文档文件图标 ====================
  { name: 'Document', component: Document, category: 'document' },
  { name: 'DocumentAdd', component: DocumentAdd, category: 'document' },
  { name: 'DocumentChecked', component: DocumentChecked, category: 'document' },
  { name: 'DocumentDelete', component: DocumentDelete, category: 'document' },
  { name: 'DocumentCopy', component: DocumentCopy, category: 'document' },
  { name: 'DocumentRemove', component: DocumentRemove, category: 'document' },
  { name: 'Folder', component: Folder, category: 'document' },
  { name: 'FolderOpened', component: FolderOpened, category: 'document' },
  { name: 'FolderAdd', component: FolderAdd, category: 'document' },
  { name: 'FolderDelete', component: FolderDelete, category: 'document' },
  { name: 'FolderRemove', component: FolderRemove, category: 'document' },
  { name: 'FolderChecked', component: FolderChecked, category: 'document' },
  { name: 'Files', component: Files, category: 'document' },
  { name: 'Tickets', component: Tickets, category: 'document' },
  { name: 'Memo', component: Memo, category: 'document' },
  { name: 'Postcard', component: Postcard, category: 'document' },
  { name: 'Collection', component: Collection, category: 'document' },
  { name: 'Paperclip', component: Paperclip, category: 'document' },
  { name: 'Reading', component: Reading, category: 'document' },

  // ==================== 系统状态图标 ====================
  { name: 'Loading', component: Loading, category: 'status' },
  { name: 'InfoFilled', component: InfoFilled, category: 'status' },
  { name: 'SuccessFilled', component: SuccessFilled, category: 'status' },
  { name: 'QuestionFilled', component: QuestionFilled, category: 'status' },
  { name: 'WarnTriangleFilled', component: WarnTriangleFilled, category: 'status' },
  { name: 'CircleCheckFilled', component: CircleCheckFilled, category: 'status' },
  { name: 'CircleCloseFilled', component: CircleCloseFilled, category: 'status' },
  { name: 'Check', component: Check, category: 'status' },
  { name: 'CloseBold', component: CloseBold, category: 'status' },
  { name: 'Finished', component: Finished, category: 'status' },
  { name: 'Checked', component: Checked, category: 'status' },

  // ==================== 用户权限图标 ====================
  { name: 'User', component: User, category: 'user' },
  { name: 'UserFilled', component: UserFilled, category: 'user' },
  { name: 'Avatar', component: Avatar, category: 'user' },
  { name: 'Lock', component: Lock, category: 'user' },
  { name: 'Unlock', component: Unlock, category: 'user' },
  { name: 'Key', component: Key, category: 'user' },
  { name: 'Wallet', component: Wallet, category: 'user' },
  { name: 'WalletFilled', component: WalletFilled, category: 'user' },
  { name: 'GoodsFilled', component: GoodsFilled, category: 'user' },

  // ==================== 导航箭头图标 ====================
  { name: 'ArrowLeft', component: ArrowLeft, category: 'arrow' },
  { name: 'ArrowUp', component: ArrowUp, category: 'arrow' },
  { name: 'ArrowRight', component: ArrowRight, category: 'arrow' },
  { name: 'ArrowDown', component: ArrowDown, category: 'arrow' },
  { name: 'ArrowLeftBold', component: ArrowLeftBold, category: 'arrow' },
  { name: 'ArrowUpBold', component: ArrowUpBold, category: 'arrow' },
  { name: 'ArrowRightBold', component: ArrowRightBold, category: 'arrow' },
  { name: 'ArrowDownBold', component: ArrowDownBold, category: 'arrow' },
  { name: 'DArrowRight', component: DArrowRight, category: 'arrow' },
  { name: 'DArrowLeft', component: DArrowLeft, category: 'arrow' },
  { name: 'Back', component: Back, category: 'arrow' },
  { name: 'Top', component: Top, category: 'arrow' },
  { name: 'Bottom', component: Bottom, category: 'arrow' },
  { name: 'CaretLeft', component: CaretLeft, category: 'arrow' },
  { name: 'CaretTop', component: CaretTop, category: 'arrow' },
  { name: 'CaretRight', component: CaretRight, category: 'arrow' },
  { name: 'CaretBottom', component: CaretBottom, category: 'arrow' },
  { name: 'Expand', component: Expand, category: 'arrow' },
  { name: 'Fold', component: Fold, category: 'arrow' },

  // ==================== 媒体设备图标 ====================
  { name: 'VideoCamera', component: VideoCamera, category: 'media' },
  { name: 'VideoCameraFilled', component: VideoCameraFilled, category: 'media' },
  { name: 'VideoPlay', component: VideoPlay, category: 'media' },
  { name: 'VideoPause', component: VideoPause, category: 'media' },
  { name: 'Microphone', component: Microphone, category: 'media' },
  { name: 'VideoCamera', component: VideoCamera, category: 'media' },
  { name: 'Camera', component: Camera, category: 'media' },
  { name: 'CameraFilled', component: CameraFilled, category: 'media' },
  { name: 'Picture', component: Picture, category: 'media' },
  { name: 'PictureRounded', component: PictureRounded, category: 'media' },
  { name: 'PictureFilled', component: PictureFilled, category: 'media' },
  { name: 'Film', component: Film, category: 'media' },
  { name: 'Headset', component: Headset, category: 'media' },
  { name: 'Monitor', component: Monitor, category: 'media' },
  { name: 'Iphone', component: Iphone, category: 'media' },
  { name: 'Cellphone', component: Cellphone, category: 'media' },

  // ==================== 位置地图图标 ====================
  { name: 'Location', component: Location, category: 'location' },
  { name: 'LocationInformation', component: LocationInformation, category: 'location' },
  { name: 'LocationFilled', component: LocationFilled, category: 'location' },
  { name: 'MapLocation', component: MapLocation, category: 'location' },
  { name: 'AddLocation', component: AddLocation, category: 'location' },
  { name: 'DeleteLocation', component: DeleteLocation, category: 'location' },
  { name: 'Place', component: Place, category: 'location' },
  { name: 'Coordinate', component: Coordinate, category: 'location' },
  { name: 'Position', component: Position, category: 'location' },
  { name: 'Guide', component: Guide, category: 'location' },

  // ==================== 工具功能图标 ====================
  { name: 'Tools', component: Tools, category: 'tools' },
  { name: 'SetUp', component: SetUp, category: 'tools' },
  { name: 'Operation', component: Operation, category: 'tools' },
  { name: 'Switch', component: Switch, category: 'tools' },
  { name: 'SwitchButton', component: SwitchButton, category: 'tools' },
  { name: 'SwitchFilled', component: SwitchFilled, category: 'tools' },
  { name: 'MagicStick', component: MagicStick, category: 'tools' },
  { name: 'ZoomIn', component: ZoomIn, category: 'tools' },
  { name: 'ZoomOut', component: ZoomOut, category: 'tools' },
  { name: 'FullScreen', component: FullScreen, category: 'tools' },
  { name: 'ScaleToOriginal', component: ScaleToOriginal, category: 'tools' },
  { name: 'Management', component: Management, category: 'tools' },
  { name: 'Stamp', component: Stamp, category: 'tools' },
  { name: 'Briefcase', component: Briefcase, category: 'tools' },

  // ==================== 消息通知图标 ====================
  { name: 'Message', component: Message, category: 'message' },
  { name: 'MessageBox', component: MessageBox, category: 'message' },
  { name: 'Notification', component: Notification, category: 'message' },
  { name: 'Bell', component: Bell, category: 'message' },
  { name: 'BellFilled', component: BellFilled, category: 'message' },
  { name: 'MuteNotification', component: MuteNotification, category: 'message' },
  { name: 'ChatDotRound', component: ChatDotRound, category: 'message' },
  { name: 'ChatDotSquare', component: ChatDotSquare, category: 'message' },
  { name: 'ChatRound', component: ChatRound, category: 'message' },
  { name: 'ChatSquare', component: ChatSquare, category: 'message' },
  { name: 'ChatLineRound', component: ChatLineRound, category: 'message' },
  { name: 'ChatLineSquare', component: ChatLineSquare, category: 'message' },
  { name: 'Comment', component: Comment, category: 'message' },

  // ==================== 上传下载图标 ====================
  { name: 'Upload', component: Upload, category: 'upload' },
  { name: 'UploadFilled', component: UploadFilled, category: 'upload' },
  { name: 'Download', component: Download, category: 'upload' },

  // ==================== 选择器图标 ====================
  { name: 'Select', component: Select, category: 'select' },
  { name: 'SemiSelect', component: SemiSelect, category: 'select' },
  { name: 'CirclePlus', component: CirclePlus, category: 'select' },
  { name: 'CirclePlusFilled', component: CirclePlusFilled, category: 'select' },

  // ==================== 购物电商图标 ====================
  { name: 'ShoppingCart', component: ShoppingCart, category: 'shopping' },
  { name: 'ShoppingCartFull', component: ShoppingCartFull, category: 'shopping' },
  { name: 'ShoppingTrolley', component: ShoppingTrolley, category: 'shopping' },
  { name: 'ShoppingBag', component: ShoppingBag, category: 'shopping' },
  { name: 'Handbag', component: Handbag, category: 'shopping' },
  { name: 'Goods', component: Goods, category: 'shopping' },
  { name: 'Sell', component: Sell, category: 'shopping' },
  { name: 'SoldOut', component: SoldOut, category: 'shopping' },
  { name: 'Coin', component: Coin, category: 'shopping' },
  { name: 'Money', component: Money, category: 'shopping' },
  { name: 'CreditCard', component: CreditCard, category: 'shopping' },
  { name: 'PriceTag', component: PriceTag, category: 'shopping' },
  { name: 'Wallet', component: Wallet, category: 'shopping' },
  { name: 'Opportunity', component: Opportunity, category: 'shopping' },

  // ==================== 竞技游戏图标 ====================
  { name: 'Trophy', component: Trophy, category: 'game' },
  { name: 'TrophyBase', component: TrophyBase, category: 'game' },
  { name: 'Medal', component: Medal, category: 'game' },
  { name: 'GoldMedal', component: GoldMedal, category: 'game' },
  { name: 'Soccer', component: Soccer, category: 'game' },
  { name: 'Football', component: Football, category: 'game' },
  { name: 'Basketball', component: Basketball, category: 'game' },
  { name: 'Baseball', component: Baseball, category: 'game' },
  { name: 'Aim', component: Aim, category: 'game' },

  // ==================== 时间日期图标 ====================
  { name: 'Clock', component: Clock, category: 'time' },
  { name: 'AlarmClock', component: AlarmClock, category: 'time' },
  { name: 'Timer', component: Timer, category: 'time' },
  { name: 'Stopwatch', component: Stopwatch, category: 'time' },
  { name: 'Calendar', component: Calendar, category: 'time' },
  { name: 'Watch', component: Watch, category: 'time' },
  { name: 'QuartzWatch', component: QuartzWatch, category: 'time' },

  // ==================== 天气气象图标 ====================
  { name: 'Sunny', component: Sunny, category: 'weather' },
  { name: 'Cloudy', component: Cloudy, category: 'weather' },
  { name: 'PartlyCloudy', component: PartlyCloudy, category: 'weather' },
  { name: 'MostlyCloudy', component: MostlyCloudy, category: 'weather' },
  { name: 'Sunrise', component: Sunrise, category: 'weather' },
  { name: 'Sunset', component: Sunset, category: 'weather' },
  { name: 'Moon', component: Moon, category: 'weather' },
  { name: 'MoonNight', component: MoonNight, category: 'weather' },
  { name: 'Lightning', component: Lightning, category: 'weather' },
  { name: 'Drizzling', component: Drizzling, category: 'weather' },
  { name: 'Pouring', component: Pouring, category: 'weather' },
  { name: 'WindPower', component: WindPower, category: 'weather' },

  // ==================== 食物饮料图标 ====================
  { name: 'Food', component: Food, category: 'food' },
  { name: 'Coffee', component: Coffee, category: 'food' },
  { name: 'CoffeeCup', component: CoffeeCup, category: 'food' },
  { name: 'IceCream', component: IceCream, category: 'food' },
  { name: 'IceCreamRound', component: IceCreamRound, category: 'food' },
  { name: 'IceCreamSquare', component: IceCreamSquare, category: 'food' },
  { name: 'Lollipop', component: Lollipop, category: 'food' },
  { name: 'IceDrink', component: IceDrink, category: 'food' },
  { name: 'ColdDrink', component: ColdDrink, category: 'food' },
  { name: 'Grape', component: Grape, category: 'food' },
  { name: 'Watermelon', component: Watermelon, category: 'food' },
  { name: 'Pear', component: Pear, category: 'food' },
  { name: 'Apple', component: Apple, category: 'food' },
  { name: 'Cherry', component: Cherry, category: 'food' },
  { name: 'Orange', component: Orange, category: 'food' },
  { name: 'Fries', component: Fries, category: 'food' },
  { name: 'Burger', component: Burger, category: 'food' },
  { name: 'Dish', component: Dish, category: 'food' },
  { name: 'DishDot', component: DishDot, category: 'food' },
  { name: 'Mug', component: Mug, category: 'food' },
  { name: 'Goblet', component: Goblet, category: 'food' },
  { name: 'GobletFull', component: GobletFull, category: 'food' },
  { name: 'GobletSquare', component: GobletSquare, category: 'food' },
  { name: 'GobletSquareFull', component: GobletSquareFull, category: 'food' },
  { name: 'Chicken', component: Chicken, category: 'food' },
  { name: 'KnifeFork', component: KnifeFork, category: 'food' },
  { name: 'ForkSpoon', component: ForkSpoon, category: 'food' },
  { name: 'MilkTea', component: MilkTea, category: 'food' },
  { name: 'IceTea', component: IceTea, category: 'food' },
  { name: 'NoSmoking', component: NoSmoking, category: 'food' },
  { name: 'Smoking', component: Smoking, category: 'food' },

  // ==================== 交通出行图标 ====================
  { name: 'Van', component: Van, category: 'transport' },
  { name: 'Ship', component: Ship, category: 'transport' },
  { name: 'Bicycle', component: Bicycle, category: 'transport' },

  // ==================== 办公用品图标 ====================
  { name: 'Printer', component: Printer, category: 'office' },
  { name: 'Suitcase', component: Suitcase, category: 'office' },
  { name: 'SuitcaseLine', component: SuitcaseLine, category: 'office' },
  { name: 'Umbrella', component: Umbrella, category: 'office' },
  { name: 'Flag', component: Flag, category: 'office' },
  { name: 'Box', component: Box, category: 'office' },
  { name: 'Refrigerator', component: Refrigerator, category: 'office' },
  { name: 'OfficeBuilding', component: OfficeBuilding, category: 'office' },
  { name: 'School', component: School, category: 'office' },

  // ==================== 电子设备图标 ====================
  { name: 'Cpu', component: Cpu, category: 'device' },
  { name: 'Mouse', component: Mouse, category: 'device' },
  { name: 'Magnet', component: Magnet, category: 'device' },

  // ==================== 医疗健康图标 ====================
  { name: 'FirstAidKit', component: FirstAidKit, category: 'medical' },

  // ==================== 其他杂项图标 ====================
  { name: 'Link', component: Link, category: 'other' },
  { name: 'Connection', component: Connection, category: 'other' },
  { name: 'Service', component: Service, category: 'other' },
  { name: 'Compass', component: Compass, category: 'other' },
  { name: 'View', component: View, category: 'other' },
  { name: 'Hide', component: Hide, category: 'other' },
  { name: 'Promotion', component: Promotion, category: 'other' },
  { name: 'TurnOff', component: TurnOff, category: 'other' },
  { name: 'Open', component: Open, category: 'other' },
  { name: 'Discount', component: Discount, category: 'other' },
  { name: 'Odometer', component: Odometer, category: 'other' },
  { name: 'Help', component: Help, category: 'other' },
  { name: 'HelpFilled', component: HelpFilled, category: 'other' },
  { name: 'Share', component: Share, category: 'other' },
  { name: 'Present', component: Present, category: 'other' },
  { name: 'TakeawayBox', component: TakeawayBox, category: 'other' },
  { name: 'CollectionTag', component: CollectionTag, category: 'other' },
  { name: 'ReadingLamp', component: ReadingLamp, category: 'other' },
  { name: 'ToiletPaper', component: ToiletPaper, category: 'other' },

  // ==================== 品牌图标 ====================
  { name: 'ChromeFilled', component: ChromeFilled, category: 'brand' },
  { name: 'Eleme', component: Eleme, category: 'brand' },
  { name: 'ElemeFilled', component: ElemeFilled, category: 'brand' },
  { name: 'ElementPlus', component: ElementPlus, category: 'brand' },
  { name: 'Shop', component: Shop, category: 'brand' }
]

/**
 * 图标分类信息（用于分组显示）
 */
export const iconCategories = {
  core: { label: '🎯 核心常用', color: '#1677ff' },
  edit: { label: '✏️ 编辑操作', color: '#52c41a' },
  data: { label: '📊 数据图表', color: '#722ed1' },
  document: { label: '📄 文档文件', color: '#fa8c16' },
  status: { label: '⚡ 系统状态', color: '#eb2f96' },
  user: { label: '👤 用户权限', color: '#13c2c2' },
  arrow: { label: '➡️ 导航箭头', color: '#1890ff' },
  media: { label: '📷 媒体设备', color: '#f5222d' },
  location: { label: '📍 位置地图', color: '#52c41a' },
  tools: { label: '🔧 工具功能', color: '#faad14' },
  message: { label: '💬 消息通知', color: '#722ed1' },
  upload: { label: '⬆️ 上传下载', color: '#13c2c2' },
  select: { label: '✅ 选择器', color: '#1677ff' },
  shopping: { label: '🛒 购物电商', color: '#eb2f96' },
  game: { label: '🏆 竞技游戏', color: '#fa8c16' },
  time: { label: '⏰ 时间日期', color: '#1890ff' },
  weather: { label: '☀️ 天气气象', color: '#f5222d' },
  food: { label: '🍔 食物饮料', color: '#52c41a' },
  transport: { label: '🚗 交通出行', color: '#faad14' },
  office: { label: '💼 办公用品', color: '#722ed1' },
  device: { label: '💻 电子设备', color: '#13c2c2' },
  medical: { label: '🏥 医疗健康', color: '#eb2f96' },
  other: { label: '📦 其他杂项', color: '#8c8c8c' },
  brand: { label: '🏢 品牌图标', color: '#1677ff' }
}

/**
 * 根据名称获取图标组件
 * @param {string} iconName - 图标名称
 * @returns {Component|null} - Vue 组件或 null
 */
export const getIconComponent = iconName => {
  const icon = availableIcons.find(item => item.name === iconName)
  return icon ? icon.component : null
}

/**
 * 根据分类获取图标列表
 * @param {string} category - 分类名称
 * @returns {Array} - 该分类下的所有图标
 */
export const getIconsByCategory = category => {
  return availableIcons.filter(item => item.category === category)
}

/**
 * 获取所有分类名称列表
 * @returns {Array} - 分类名称数组
 */
export const getCategoryNames = () => {
  return Object.keys(iconCategories)
}
